name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: skyhaven-ltd/pipeline-engineering-github-actions/.github/workflows/reusable-lint.yml@f5851503b5a5f3f08b349bca15a9324eae238ed1 # v1.0.0
    with:
      flavor: terraform
      config_file: .github/validation/.mega-linter.yml
